//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.03 at 08:32:28 AM PET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:sunat:names:specification:ubl:peru:schema:xsd:VoidedDocuments-1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
        @XmlNs(namespaceURI = "urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1", prefix = "sac"),
        @XmlNs(namespaceURI = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", prefix = "cac"),
        @XmlNs(namespaceURI = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", prefix = "cbc"),
//        @XmlNs(namespaceURI = "urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2", prefix = "udt"),
//        @XmlNs(namespaceURI = "urn:un:unece:uncefact:documentation:2", prefix = "ccts"),
        @XmlNs(namespaceURI = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2", prefix = "ext"),
//        @XmlNs(namespaceURI = "urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2", prefix = "qdt"),
        @XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix = "ds"),
        @XmlNs(namespaceURI = "urn:sunat:names:specification:ubl:peru:schema:xsd:VoidedDocuments-1", prefix = ""),
        @XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi")

})
package sunat.names.specification.ubl.peru.schema.xsd.voideddocuments_1;

import javax.xml.bind.annotation.XmlNs;